"""change tenant_name to name

Revision ID: 0115fb3e51eb
Revises: ad07af581d82
Create Date: 2025-04-28 12:19:57.181811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0115fb3e51eb'
down_revision: Union[str, None] = 'ad07af581d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'tenant_name', new_column_name='name')
    #op.drop_column('tenants', 'tenant_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tenant_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'name')
    # ### end Alembic commands ###
