"""add tenant_id back in

Revision ID: 0df8242fc37f
Revises: 5472ad02b399
Create Date: 2025-04-28 21:48:35.522504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df8242fc37f'
down_revision: Union[str, None] = '5472ad02b399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable=True
    op.add_column('tenants', sa.Column('tenant_id', sa.String(), nullable=True))

    # Step 2: Populate it with an arbitrary/default value
    op.execute("UPDATE tenants SET tenant_id = 'temp-id' WHERE tenant_id IS NULL")

    # Step 3: Alter column to be nullable=False
    op.alter_column('tenants', 'tenant_id', nullable=False)    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'tenant_id')
    # ### end Alembic commands ###
