"""Add scheduler and DPSK orchestrator tables

Revision ID: 144fcbb9c5e2
Revises: f4g5h6i7j8k9
Create Date: 2026-01-18 13:23:33.173822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '144fcbb9c5e2'
down_revision: Union[str, None] = 'f4g5h6i7j8k9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('callable_path', sa.String(), nullable=False),
    sa.Column('callable_kwargs', sa.JSON(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dpsk_orchestrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('venue_id', sa.String(), nullable=True),
    sa.Column('site_wide_pool_id', sa.String(), nullable=False),
    sa.Column('site_wide_pool_name', sa.String(), nullable=True),
    sa.Column('site_wide_identity_group_id', sa.String(), nullable=True),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_delete', sa.Boolean(), nullable=True),
    sa.Column('auto_discover_enabled', sa.Boolean(), nullable=True),
    sa.Column('include_patterns', sa.JSON(), nullable=True),
    sa.Column('exclude_patterns', sa.JSON(), nullable=True),
    sa.Column('webhook_id', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_discovery_at', sa.DateTime(), nullable=True),
    sa.Column('discovered_pools_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scheduled_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orchestrator_source_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orchestrator_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.String(), nullable=False),
    sa.Column('pool_name', sa.String(), nullable=True),
    sa.Column('identity_group_id', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('passphrase_count', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orchestrator_id'], ['dpsk_orchestrators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orchestrator_sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orchestrator_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('trigger_activity_id', sa.String(), nullable=True),
    sa.Column('source_pool_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('added_count', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.Column('flagged_for_removal', sa.Integer(), nullable=True),
    sa.Column('orphans_found', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('pools_scanned', sa.Integer(), nullable=True),
    sa.Column('pools_discovered', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orchestrator_id'], ['dpsk_orchestrators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passphrase_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orchestrator_id', sa.Integer(), nullable=False),
    sa.Column('source_pool_id', sa.String(), nullable=False),
    sa.Column('source_pool_name', sa.String(), nullable=True),
    sa.Column('source_passphrase_id', sa.String(), nullable=True),
    sa.Column('source_username', sa.String(), nullable=True),
    sa.Column('source_identity_id', sa.String(), nullable=True),
    sa.Column('target_passphrase_id', sa.String(), nullable=True),
    sa.Column('target_identity_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('suggested_source_pool_id', sa.String(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('passphrase_preview', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orchestrator_id'], ['dpsk_orchestrators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passphrase_mappings')
    op.drop_table('orchestrator_sync_events')
    op.drop_table('orchestrator_source_pools')
    op.drop_table('scheduled_job_runs')
    op.drop_table('dpsk_orchestrators')
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###
