"""Add userapi and tenant structure

Revision ID: 3d781732d6fb
Revises: 21b9f3be624d
Create Date: 2025-04-28 09:19:51.288332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d781732d6fb'
down_revision: Union[str, None] = '21b9f3be624d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_api_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_api_keys', ['active_api_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_api_key_id')
    # ### end Alembic commands ###
