"""unique tenant name per user

Revision ID: 5472ad02b399
Revises: 0115fb3e51eb
Create Date: 2025-04-28 13:42:20.827351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5472ad02b399'
down_revision: Union[str, None] = '0115fb3e51eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_tenant_name', 'tenants', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_tenant_name', 'tenants', type_='unique')
    # ### end Alembic commands ###
