"""client secret to shared secret

Revision ID: 8f3def932197
Revises: 0df8242fc37f
Create Date: 2025-04-28 22:57:13.422746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3def932197'
down_revision: Union[str, None] = '0df8242fc37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'encrypted_client_secret',new_column_name='encrypted_shared_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'encrypted_shared_secret',new_column_name='encrypted_client_secret')

    # ### end Alembic commands ###
