"""change instancename to tenantname

Revision ID: ad07af581d82
Revises: eefef24bad69
Create Date: 2025-04-28 11:02:52.023917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad07af581d82'
down_revision: Union[str, None] = 'eefef24bad69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tenant_name', sa.String(), nullable=False))
    op.drop_column('tenants', 'instance_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('instance_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'tenant_name')
    # ### end Alembic commands ###
