"""Add domain to companies

Revision ID: e92ecd1fe4cf
Revises: 424461e687d8
Create Date: 2025-04-27 07:11:51.718008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92ecd1fe4cf'
down_revision: Union[str, None] = '424461e687d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('domain', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'companies', ['domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'domain')
    # ### end Alembic commands ###
