"""Add secondary_tenant_id to User

Revision ID: f3bf533425b6
Revises: 8f3def932197
Create Date: 2025-06-10 10:42:33.537014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bf533425b6'
down_revision: Union[str, None] = '8f3def932197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secondary_tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tenants', ['secondary_tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'secondary_tenant_id')
    # ### end Alembic commands ###
