#!/usr/bin/env python3
"""
List identities RuckusONE named for itself, paired with their real twin.

READ-ONLY. It deletes nothing and offers no way to. Deciding what to remove
from a live property is a separate job with a separate blast radius; this
exists so that decision is made against a checked list rather than a guess.

An identity named "DPSK_User_2Uj85Sj1xH_1" was never named by this import.
R1 invented it when a passphrase create could not attach to the identity we
asked for, then update_identity_descriptions stamped the resident's Cloudpath
GUID onto it -- so it looks like a real resident and later runs match it.

For each such identity this prints the GUID it carries and the properly named
identity carrying the SAME GUID. A pair means the resident is intact under
the real name and the invented one is safe to remove. A LONE invented name means no real twin exists: that identity is the only
record of the resident, and it still holds a working passphrase. Deleting it
disconnects them. Those are reported separately and must be identified
first -- by GUID against the Cloudpath export where one exists, or by
matching the passphrase value where it does not -- then renamed, never
deleted.

Usage:
    docker compose exec backend python scripts/report_autonamed_identities.py \
        --controller 16 [--tenant <ec-id>] [--group <identity-group-id>] [--csv out.csv]
"""

import argparse
import asyncio
import csv
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from workflow.phases.dpsk_usernames import is_r1_autogenerated_name


async def identities_in(r1, tenant, group_id):
    out, page = [], 0
    while page < 50:
        r = await r1.identity.get_identities_in_group(
            group_id=group_id, tenant_id=tenant, page=page, size=500
        )
        items = r.get("content", r.get("data", [])) if isinstance(r, dict) else (r or [])
        out.extend(items)
        if not isinstance(r, dict) or not items:
            break
        # R1 caps this endpoint at 100 per page regardless of the size asked
        # for -- verified: size=500 returns 100. So "fewer rows than I asked
        # for" is NOT end-of-data here, and using it as one silently reads
        # only the first 100 identities of a 250-resident group. Trust the
        # server's own last/totalPages instead.
        if r.get("last") is True:
            break
        total_pages = r.get("totalPages")
        page += 1
        if isinstance(total_pages, int) and page >= total_pages:
            break
    return out


async def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--controller", type=int, required=True)
    ap.add_argument("--tenant", default=None)
    ap.add_argument("--group", default=None, help="one identity group id; default all")
    ap.add_argument("--csv", default=None)
    args = ap.parse_args()

    from database import SessionLocal
    from clients.r1_client import create_r1_client_from_controller

    db = SessionLocal()
    try:
        r1 = create_r1_client_from_controller(args.controller, db)
        resp = await r1.identity.query_identity_groups(
            tenant_id=args.tenant, page=0, size=1000
        )
        groups = resp.get("content", resp.get("data", [])) if isinstance(resp, dict) else resp
        if args.group:
            groups = [g for g in groups if g.get("id") == args.group]
        if not groups:
            print("No identity groups found.")
            return 1

        rows, lone = [], []
        for g in groups:
            gid, gname = g.get("id"), g.get("name")
            if not gid:
                continue
            ids = await identities_in(r1, args.tenant, gid)
            by_guid = defaultdict(list)
            for rec in ids:
                if rec.get("description"):
                    by_guid[rec["description"]].append(rec)

            invented = [r for r in ids if is_r1_autogenerated_name(r.get("name"))]
            if not invented:
                continue
            print(f"\n{gname}  ({len(invented)} of {len(ids)} identities were named by R1)")
            for rec in sorted(invented, key=lambda r: r.get("name") or ""):
                guid = rec.get("description") or ""
                twins = [
                    t for t in by_guid.get(guid, [])
                    if t["id"] != rec["id"] and not is_r1_autogenerated_name(t.get("name"))
                ]
                if twins:
                    real = twins[0]
                    print(f"  {rec['name']:26} -> real twin {real['name']:20} guid {guid[-12:]}")
                    rows.append({
                        "group": gname, "invented_name": rec["name"],
                        "invented_id": rec["id"], "real_name": real["name"],
                        "real_id": real["id"], "cloudpath_guid": guid,
                    })
                else:
                    # No twin AND (usually) no GUID: nothing in R1 says which
                    # resident this is. It still holds a passphrase, so
                    # someone may be connected on it. The only way back to a
                    # name is the passphrase VALUE, which appears in the
                    # Cloudpath export -- match it there rather than guessing.
                    note = ("no GUID either — match its passphrase against "
                            "the export to identify the resident"
                            if not guid else
                            "has a GUID — look it up in the export and rename")
                    print(f"  {rec['name']:26} -> NO real twin; {note}")
                    lone.append({
                        "group": gname, "invented_name": rec["name"],
                        "invented_id": rec["id"], "real_name": "",
                        "real_id": "", "cloudpath_guid": guid,
                    })

        print(f"\n{len(rows)} invented identity(s) have a real twin and are safe to remove.")
        if lone:
            print(
                f"{len(lone)} have NO real twin. Each still holds a passphrase, "
                f"so deleting one disconnects whoever is using it and loses the "
                f"only record that it existed. Identify them first: a GUID can "
                f"be looked up in the Cloudpath export directly; without one, "
                f"match the passphrase value instead."
            )

        if args.csv:
            with open(args.csv, "w", newline="") as fh:
                w = csv.DictWriter(fh, fieldnames=[
                    "group", "invented_name", "invented_id",
                    "real_name", "real_id", "cloudpath_guid",
                ])
                w.writeheader()
                w.writerows(rows + lone)
            print(f"Wrote {args.csv}")
        return 0
    finally:
        db.close()


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
