#!/usr/bin/env python3
"""
Auto-named identity regression test.

WHAT WENT WRONG

create_passphrase sends `identityId` OR `username`, never both:

    if identity_id:
        payload["identityId"] = identity_id
    elif user_name:
        payload["username"] = user_name

That exclusivity is deliberate -- sending a username makes R1 mint a NEW
identity and fail with GENERAL-010 when one already exists -- but it means a
request carrying identityId has NO name to fall back on. When R1 could not
honour the id (the identity group had no DPSK pool attached) it minted a
persona anyway and invented a name: "DPSK_User_2Uj85Sj1xH_1".

Then update_identity_descriptions stamped the resident's Cloudpath GUID onto
that debris, so the NEXT run matched the GUID, found the debris, passed its
id, and attached another passphrase to the wrong identity. It compounds.

Measured on a live tenant: 254 identities for 161 residents. 93 Cloudpath
GUIDs each carried by exactly TWO identities -- one correctly named
("8155400502000993") and one invented ("DPSK_User_2Uj84q7W0c_1").

WHAT THIS GUARDS

  1. create_passphrase REFUSES a call with neither username nor identity id,
     rather than letting R1 name the resident for us.
  2. A GUID carried by both a real and an invented name resolves to the REAL
     one, whichever was seen first.
  3. A file entry never matches an invented name by name either.
  4. The invented names are reported, so they can be cleaned up.
  5. A normal identity is still matched exactly as before.

Usage:
    docker compose exec backend python scripts/test_no_autonamed_identities.py
"""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from r1api.services.dpsk import DpskService
from workflow.phases.dpsk_usernames import is_r1_autogenerated_name


def check(label, ok, detail=""):
    print(f"  {'ok  ' if ok else 'FAIL'}  {label}" + (f"  -- {detail}" if detail else ""))
    return 0 if ok else 1


def resolve(pp_guid, pp_name, identities):
    """
    validate's resolution order, with the auto-named rule applied -- lifted so
    it can be exercised without standing up the phase.
    """
    by_guid, by_name = {}, {}
    autonamed = []
    for rec in identities:
        name, desc = rec["name"], rec.get("description") or ""
        by_name[name] = rec
        if not desc:
            continue
        prior = by_guid.get(desc)
        if prior and is_r1_autogenerated_name(name):
            autonamed.append(name); continue
        if prior and is_r1_autogenerated_name(prior["name"]):
            autonamed.append(prior["name"]); by_guid[desc] = rec; continue
        if not prior:
            by_guid[desc] = rec

    info = by_guid.get(pp_guid) or by_name.get(pp_name)
    if info and is_r1_autogenerated_name(info["name"]):
        info = None
    return info, autonamed


async def main() -> int:
    failures = 0
    print("Auto-named identities\n")

    # 1. the hard guarantee
    svc = DpskService.__new__(DpskService)
    try:
        await svc.create_passphrase(pool_id="p", passphrase="x")
        failures += check("create_passphrase refuses a nameless call", False, "no raise")
    except ValueError as e:
        failures += check(
            "create_passphrase refuses a nameless call",
            "invents a name" in str(e), str(e)[:70],
        )

    GUID = "AccountDpsk-9bfdc969fe58"
    REAL = {"id": "i-real", "name": "8155400502000993", "description": GUID}
    FAKE = {"id": "i-fake", "name": "DPSK_User_2Uj85Sj1xH_1", "description": GUID}

    # 2. real name wins, in BOTH insertion orders
    for order, label in ((["FAKE", "REAL"], "debris seen first"),
                         (["REAL", "FAKE"], "real seen first")):
        ids = [FAKE if x == "FAKE" else REAL for x in order]
        info, auto = resolve(GUID, "8155400502000993", ids)
        failures += check(
            f"the real identity wins when the {label}",
            info is not None and info["id"] == "i-real"
            and auto == ["DPSK_User_2Uj85Sj1xH_1"],
            f"matched={info and info['id']}, autonamed={auto}",
        )

    # 3. never match an invented name by name either
    info, _ = resolve("no-such-guid", "DPSK_User_2Uj85Sj1xH_1", [FAKE])
    failures += check(
        "a file entry never resolves to an invented name",
        info is None, f"matched={info}",
    )

    # 4. a normal identity still matches
    info, auto = resolve(GUID, "8155400502000993", [REAL])
    failures += check(
        "a normal identity is matched exactly as before",
        info is not None and info["id"] == "i-real" and auto == [],
    )

    # 5. the detector itself
    failures += check(
        "the detector recognises R1 names and leaves real ones alone",
        is_r1_autogenerated_name("DPSK_User_abc_1")
        and not is_r1_autogenerated_name("8155400502000993")
        and not is_r1_autogenerated_name("4021_ultrafast")
        and not is_r1_autogenerated_name(None),
    )

    print(f"\n{'FAILED' if failures else 'All checks passed'}"
          f"{f' ({failures})' if failures else ''}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
